BUILDDIR := ${CURDIR}/build
TOP := __CAAS_TOP
SOURCES := __CAAS_SOURCES
XDC := __CAAS_XDC

PART := __CAAS_PART

LOGFILE := ${BUILDDIR}/top.log

# Build design
all: ${BUILDDIR}/${TOP}.bit

${BUILDDIR}:
	mkdir -m 777 -p ${BUILDDIR} && chown -R nobody ${BUILDDIR}

${BUILDDIR}/vivado.tcl:
	cat << EOF > $@
# vivado.tcl generated for caas
EOF


${BUILDDIR}/${TOP}.bit: ${BUILDDIR}/vivado.tcl
	vivado -mode batch $< > ${LOGFILE} 2>&1

.PHONY: clean
clean:
	rm -rf ${BUILDDIR}
